---
- name: Battleshiphp daemon
  cron: >
    job="run-one php {{ application_root }}/bin/battleship.php 192.168.56.82 1>> {{ application_root }}/logs/battleshiphp-daemon.log 2>&1"
    state=present
    name="Battleshiphp daemon"
